### ISSUE TITLE
Closing connection - Device not available

### ISSUE THREAD

**Issue by sftgunner** [timlaing/modbus_local_gateway#19]
Currently getting the error `[custom_components.modbus_local_gateway.tcp_client] Closing connection - Device not available AsyncModbusTcpClientGateway 10.0.22.250:502 [1]`.
I am using the same WaveShare Wi-Fi to RS485 as recommended, along with my Heatmiser Edge thermostat. I've got a very barebones yaml set up, and keep getting the error above. I initially saw it working briefly, but haven't seen it function again. The native HomeAssistant MODBUS integration continues to be able to interact with the device fine. Any idea what might be causing this?

Basic yaml:
```
device:
  manufacturer: Heatmiser
  model: Edge
  operation_mode:
    title: Current operation mode
    address: 33
    control: number
    icon: mdi:serial-port
    precision: 0
    number:
      min: 0
      max: 5

entities:
  machine_status:
    title: Code version number
    address: 1
```
