### ISSUE TITLE
Multiplier on float register

### ISSUE THREAD

**Issue by fhainz** [timlaing/modbus_local_gateway#44]
Hello!

My fronius inverter outputs the total energy in a float holding register in Wh. I would like to convert this to kWh using the multiplier. But as soon as I enter multiplier, the entity is no longer provided by the integration. 

```
energy_ac:
  name: energy_ac
  address: 40101
  float: true
  size: 2
  multiplier: 0.001
  unit_of_measurement: kWh
  device_class: energy
  state_class: total_increasing
```
