### ISSUE TITLE
Sensor Values suddenly wrong.

### ISSUE THREAD

**Issue by maniac-semal** [timlaing/modbus_local_gateway#66]
## System Information

version | core-2025.5.3
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.3
os_name | Linux
os_version | 6.12.23-haos
arch | x86_64
timezone | Europe/Berlin
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4966
Installed Version | 2.0.5
Stage | running
Available Repositories | 2078
Downloaded Repositories | 89

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 15.2
-- | --
update_channel | stable
supervisor_version | supervisor-2025.05.3
agent_version | 1.7.2
docker_version | 28.0.4
disk_total | 219.4 GB
disk_used | 46.1 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon (0.17.4), BirdNET-pi (2025.04.08), EMQX (0.7.5), Git pull (8.0.1), MQTT Explorer (browser-1.0.1), Music Assistant Server (2.5.4), NSPanel Manager (1.0.4), Piper (1.5.4), SQLite Web (4.3.1), Terminal & SSH (9.17.0), Zigbee2MQTT (2.4.0-1), chrony (5.1.0), vosk (1.6.1), microwakeword (1.0.0), Firefly iii (6.2.16), Firefly iii FinTS Importer (1.3.0-4), ESPHome Device Builder (2025.5.2), Silicon Labs Flasher (0.3.2), Matter Server (8.0.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 50
views | 16
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), eno1 (enabled, default, auto), hassio (disabled), docker0 (disabled), veth45992ab (disabled), vethe3215b7 (disabled), veth2ab82c2 (disabled), vethd0761e7 (disabled), veth39e9341 (disabled), veth909d15c (disabled), veth5ec1b4f (disabled), veth5d4d8a4 (disabled), vetha27c7fc (disabled), veth797a77c (disabled), veth6d00223 (disabled), veth1c254d9 (disabled), veth8a9aef3 (disabled), vethfeaf824 (disabled), veth9576f68 (disabled), veth252e8d7 (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), eno1 (10.18.2.1/16), hassio (172.30.32.1/23), docker0 (172.30.232.1/23), veth45992ab (), vethe3215b7 (), veth2ab82c2 (), vethd0761e7 (), veth39e9341 (), veth909d15c (), veth5ec1b4f (), veth5d4d8a4 (), vetha27c7fc (), veth797a77c (), veth6d00223 (), veth1c254d9 (), veth8a9aef3 (), vethfeaf824 (), veth9576f68 (), veth252e8d7 ()
ipv6_addresses | lo (::1/128), eno1 (fe80::cdb9:3d17:d901:8905/64), hassio (fe80::4864:feff:fe9a:c97c/64), docker0 (fe80::942e:a6ff:fe4c:a776/64), veth45992ab (fe80::8fa:1ff:fe75:845b/64), vethe3215b7 (fe80::c073:b3ff:fe34:a328/64), veth2ab82c2 (fe80::f0ab:e1ff:fe9c:47b0/64), vethd0761e7 (fe80::c4e3:b9ff:fe8c:76c8/64), veth39e9341 (fe80::470:25ff:fe03:6e7e/64), veth909d15c (fe80::3cb4:95ff:feb6:2562/64), veth5ec1b4f (fe80::3cb1:feff:fe52:a90c/64), veth5d4d8a4 (fe80::20fe:10ff:fe12:b5b/64), vetha27c7fc (fe80::34bf:6aff:fe38:1c93/64), veth797a77c (fe80::a419:b2ff:fea7:4ed5/64), veth6d00223 (fe80::c48:b3ff:fe24:9edd/64), veth1c254d9 (fe80::f8df:baff:fe94:98d3/64), veth8a9aef3 (fe80::60fa:8cff:fe28:1d6e/64), vethfeaf824 (fe80::4c9c:b1ff:fe71:180a/64), veth9576f68 (fe80::b469:9aff:fe8a:544f/64), veth252e8d7 (fe80::54df:96ff:fe5a:ae26/64)
announce_addresses | 10.18.2.1, fe80::cdb9:3d17:d901:8905

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 29. Mai 2025 um 01:08
-- | --
current_recorder_run | 9. Juni 2025 um 00:08
estimated_db_size | 1299.83 MiB
database_engine | sqlite
database_version | 3.48.0

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any [previous issues](https://github.com/timlaing/modbus_local_gateway/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Since the latest update all my Analog Sensors are suddenly showing wrong data. Seems they are rounded to the next base 10 value (so 10, 20, 30, and so on). Rolling back to the previous version fixes the issue for now.

Here are some of the sensors as example:

 ```
 inlet_temperature:
    name: "Rücklauf-Temperatur"
    address: 0x000E
    precision: 1
    multiplier: 0.1
    device_class: temperature
    unit_of_measurement: °C
    icon: mdi:water-thermometer

  hotwater_temp:
    name: "Warmwasser-Temperatur"
    address: 0x000F
    precision: 1
    multiplier: 0.1
    device_class: temperature
    unit_of_measurement: °C
    icon: mdi:water-thermometer

  ambi_temperature:
    name: "Umgebungs-Temperatur"
    address: 0x0011
    precision: 1
    multiplier: 0.5
    device_class: temperature
    unit_of_measurement: °C
    icon: mdi:sun-thermometer
    
  outlet_temperature:
    name: "Vorlauf-Temperatur"
    address: 0x0012
    precision: 1
    multiplier: 0.1
    device_class: temperature
    unit_of_measurement: °C
    icon: mdi:water-thermometer
```

### Reproduction steps

Update to version 2026.6.0

### Debug logs

```text
-
```
